name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y fakeroot musl-tools
      - uses: actions/checkout@v2
      - run: cargo build $CARGO_ARGS
      - run: cargo test $CARGO_ARGS
